name: Run Unit Tests
# description: For any pushes to the main branch, run all unit tests and then, if testing is sucessful, build a .jar file.

on:
  push:
    branches: [ "main"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write  # Needs to write extended output of tests

    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Run all unit tests
      run: ./gradlew test

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@170bf24d20d201b842d7a52403b73ed297e6645b
      if: always()  # Want to run this step even if the testing step itself fails
      with:
        comment_mode: off  # Don't want to leave a comment on related PRs
        files: |
          headless/build/test-results/**/*.xml

  # If tests pass, make a .jar file available to download
  build:
    runs-on: ubuntu-latest
    needs: test  # Will be skipped if tests fail
    
    permissions:
      contents: read

    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UniSim Java Package
        path: lwjgl3/build/libs/*  # Upload generated Java file ('*' used in case output file name changes)
